### ISSUE TITLE
Feature Request: Keyboard shortcut for "Mark One" command.

### ISSUE THREAD

**Issue by OxyMauron** [Dotsarecool/DiztinGUIsh#39]
This would be useful when manually labeling code with opcode/operand labels.

**Comment by binary1230** [comment]
oh man yea I just realized a bunch of the keyboard shortcuts aren't in the menus

here's a list of the keyboard shortcuts
https://htmlpreview.github.io/?https://raw.githubusercontent.com/Dotsarecool/DiztinGUIsh/master/DiztinGUIsh/dist/help.html

for "Mark One", it's the K key

**Comment by binary1230** [comment]
ok, so looks like we can't add single-character (i.e. non-modified with CTRL/SHIFT/ALT/etc) keyboard shortcut labels in the menus

I'll see if I can either work around that or, maybe have a quick way to open up keyboard shortcuts.  or maybe just shove the keyboard shortcut names into the menu items as a workaround.  I'm always hunting around for the keyboard shortcuts too

**Comment by binary1230** [comment]
![image](https://user-images.githubusercontent.com/5413064/109398922-a550be00-790d-11eb-8e14-9ddb62dffb59.png)
yea cool turns out this was pretty simple, I'll check it in it'll be in the next build

**Comment by OxyMauron** [comment]
Looks great. 👍
