### ISSUE TITLE
NullReferenceException when clearing a set label

### ISSUE THREAD

**Issue by VitorVilela7** [Dotsarecool/DiztinGUIsh#5]
When you set a label at a certain location and afterwards you clear it, you won't be able to save the project anymore because an error message appears with the NullReferenceException text description.

![image](https://user-images.githubusercontent.com/12776674/56854723-995ed400-6911-11e9-85cf-17fe8bd7494b.png)

If a user removes a label on the disassembly, make sure to the tool remove the label reference as well for not causing that.

The easiest way to trigger it is creating a new project and erase one of the default generated labels for vector (Reset, NMI, IRQ, etc.).

**Comment by Dotsarecool** [comment]
Fixed in [v1.0.0.4](https://github.com/Dotsarecool/DiztinGUIsh/commit/4d62af5f3a7e81468f60437d790d0842f4a87fc9#diff-6aa464eed80481a1b714235fb0d9cb7dR59)!
