### ISSUE TITLE
Marking Many - bytes should be set automaticly

### ISSUE THREAD

**Issue by blackerking** [Dotsarecool/DiztinGUIsh#58]
When adding a higher value as end-offset it changes the start address(Offset).

It would be more userfriendly if the bytes are variable and start and end address are not set via the number of bytes.

Error in declared in pictures:
![grafik](https://user-images.githubusercontent.com/2019363/120084974-d7bcb380-c0d4-11eb-8c1f-9670cb9cb161.png)
let's see we'd like to declare to D400...
![grafik](https://user-images.githubusercontent.com/2019363/120084985-e6a36600-c0d4-11eb-97b2-2c9a382cb921.png)
whoops... start-address changed

**Comment by binary1230** [comment]
started on this in wip_fix_markmany_ux branch. not quite there
