### ISSUE TITLE
Marking Many Window - safe last type

### ISSUE THREAD

**Issue by blackerking** [Dotsarecool/DiztinGUIsh#59]
I was marking data or graphics of my project rom and I lost many time choosing the right type in the mark many window.
It would be neat if the last used type is stored in memory while the project / programm is open.

![grafik](https://user-images.githubusercontent.com/2019363/120085112-b27c7500-c0d5-11eb-8238-f333fffc6525.png)

**Comment by binary1230** [comment]
started on this in wip_fix_markmany_ux branch. not quite there
