### ISSUE TITLE
Data type "Dword pointer" reverts to "graphics" after saving/loading project

### ISSUE THREAD

**Issue by ChristopheF** [Dotsarecool/DiztinGUIsh#62]
How to reproduce:
Open a project
Mark some bytes as "Dword pointer" type
Save the project and close DistinGUIsh
Load the project
The bytes are now marked as "Graphics" instead of "Dword pointer".

**Comment by binary1230** [comment]
sorry about that, was a really silly mistake. latest release should have that fixed up for you
